//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public Advert()
        {
            this.CampaignAdverts = new HashSet<CampaignAdvert>();
        }
    
        public int AdvertId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string AdvertName { get; set; }
        public string AdvertDescription { get; set; }
        public string Brand { get; set; }
        public string MediaFileLocation { get; set; }
        public bool UploadedToMediaServer { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public Nullable<int> CampaignProfile_CampaignProfileId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Script { get; set; }
        public string ScriptFileLocation { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CampaignProfile CampaignProfile { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CampaignAdvert> CampaignAdverts { get; set; }
    }
}
