//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetail
    {
        public int Id { get; set; }
        public int BillingId { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string ExpiryMonth { get; set; }
        public string ExpiryYear { get; set; }
        public string NameOfCard { get; set; }
        public string SecurityCode { get; set; }
        public string BillingAddress { get; set; }
        public string BillingTown { get; set; }
        public string BillingPostcode { get; set; }
        public string PaypalEmail { get; set; }
        public string PaypalTranID { get; set; }
    
        public virtual Billing Billing { get; set; }
    }
}
