//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketAudit
    {
        public BucketAudit()
        {
            this.BucketAuditRows = new HashSet<BucketAuditRow>();
        }
    
        public int Id { get; set; }
        public int BucketId { get; set; }
        public string MSISDN { get; set; }
        public string BucketPeriodStart { get; set; }
        public string TargetDeliveryServer { get; set; }
        public bool Processed { get; set; }
    
        public virtual ICollection<BucketAuditRow> BucketAuditRows { get; set; }
    }
}
