//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignProfileProductsService
    {
        public int CampaignProfileProductsServicesId { get; set; }
        public int CampaignProfileId { get; set; }
        public string Food { get; set; }
        public string SweetSaltySnacks { get; set; }
        public string AlcoholicDrinks { get; set; }
        public string NonAlcoholicDrinks { get; set; }
        public string Householdproducts { get; set; }
        public string ToiletriesCosmetics { get; set; }
        public string PharmaceuticalChemistsProducts { get; set; }
        public string TobaccoProducts { get; set; }
        public string PetsPetFood { get; set; }
        public string ShoppingRetailClothing { get; set; }
        public string DIYGardening { get; set; }
        public string AppliancesOtherHouseholdDurables { get; set; }
        public string ElectronicsOtherPersonalItems { get; set; }
        public string CommunicationsInternet { get; set; }
        public string FinancialServices { get; set; }
        public string HolidaysTravel { get; set; }
        public string SportsLeisure { get; set; }
        public string Motoring { get; set; }
    
        public virtual CampaignProfile CampaignProfile { get; set; }
    }
}
