//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignProfileRadio
    {
        public int CampaignProfileRadioId { get; set; }
        public int CampaignProfileId { get; set; }
        public string National { get; set; }
        public string Local { get; set; }
        public string Music { get; set; }
        public string Sport { get; set; }
        public string Talk { get; set; }
    
        public virtual CampaignProfile CampaignProfile { get; set; }
    }
}
