//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignProfileReport
    {
        public CampaignProfileReport()
        {
            this.CampaignProfileMSISDNs = new HashSet<CampaignProfileMSISDN>();
        }
    
        public int CampaignProfileReportId { get; set; }
        public int CampaignProfileId { get; set; }
        public System.DateTime CampaignProfileReportDateTime { get; set; }
        public int Demographics { get; set; }
        public int Attitudes { get; set; }
        public int Cinemas { get; set; }
        public int Internets { get; set; }
        public int Mobiles { get; set; }
        public int Presses { get; set; }
        public int Services { get; set; }
        public int Radio { get; set; }
        public int TV { get; set; }
        public int CampaignTimeSettings { get; set; }
        public int UserTimeSettings { get; set; }
        public int TotalMatches { get; set; }
        public int Advert { get; set; }
    
        public virtual CampaignProfile CampaignProfile { get; set; }
        public virtual ICollection<CampaignProfileMSISDN> CampaignProfileMSISDNs { get; set; }
    }
}
