//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignProfileAdvert
    {
        public int CampaignProfileAdvertsId { get; set; }
        public int CampaignProfileId { get; set; }
        public string Food { get; set; }
        public string SweetSaltySnacks { get; set; }
        public string AlcoholicDrinks { get; set; }
        public string NonAlcoholicDrinks { get; set; }
        public string Householdproducts { get; set; }
        public string ToiletriesCosmetics { get; set; }
        public string PharmaceuticalChemistsProducts { get; set; }
        public string TobaccoProducts { get; set; }
        public string PetsPetFood { get; set; }
        public string ShoppingRetailClothing { get; set; }
        public string DIYGardening { get; set; }
        public string AppliancesOtherHouseholdDurables { get; set; }
        public string ElectronicsOtherPersonalItems { get; set; }
        public string CommunicationsInternet { get; set; }
        public string FinancialServices { get; set; }
        public string HolidaysTravel { get; set; }
        public string SportsLeisure { get; set; }
        public string Motoring { get; set; }
        public string Newspapers { get; set; }
        public string Magazines { get; set; }
        public string TV { get; set; }
        public string Radio { get; set; }
        public string Cinema { get; set; }
        public string SocialNetworking { get; set; }
        public string GeneralUse { get; set; }
        public string Shopping { get; set; }
        public string Fitness { get; set; }
        public string Holidays { get; set; }
        public string Environment { get; set; }
        public string GoingOut { get; set; }
        public string FinancialProducts { get; set; }
        public string Religion { get; set; }
        public string Fashion { get; set; }
        public string Music { get; set; }
    
        public virtual CampaignProfile CampaignProfile { get; set; }
    }
}
