//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignProfileAttitude
    {
        public int CampaignProfileAttitudeId { get; set; }
        public int CampaignProfileId { get; set; }
        public string Fitness { get; set; }
        public string Holidays { get; set; }
        public string Environment { get; set; }
        public string GoingOut { get; set; }
        public string FinancialStabiity { get; set; }
        public string Religion { get; set; }
        public string Fashion { get; set; }
        public string Music { get; set; }
    
        public virtual CampaignProfile CampaignProfile { get; set; }
    }
}
