//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignProfile
    {
        public CampaignProfile()
        {
            this.Adverts = new HashSet<Advert>();
            this.Billings = new HashSet<Billing>();
            this.BucketAuditRows = new HashSet<BucketAuditRow>();
            this.CampaignAdverts = new HashSet<CampaignAdvert>();
            this.CampaignAudits = new HashSet<CampaignAudit>();
            this.CampaignProfileAdverts = new HashSet<CampaignProfileAdvert>();
            this.CampaignProfileAttitudes = new HashSet<CampaignProfileAttitude>();
            this.CampaignProfileCinemas = new HashSet<CampaignProfileCinema>();
            this.CampaignProfileDateSettings = new HashSet<CampaignProfileDateSetting>();
            this.CampaignProfileDemographics = new HashSet<CampaignProfileDemographic>();
            this.CampaignProfileInternets = new HashSet<CampaignProfileInternet>();
            this.CampaignProfileMobiles = new HashSet<CampaignProfileMobile>();
            this.CampaignProfilePresses = new HashSet<CampaignProfilePress>();
            this.CampaignProfileProductsServices = new HashSet<CampaignProfileProductsService>();
            this.CampaignProfileRadios = new HashSet<CampaignProfileRadio>();
            this.CampaignProfileReports = new HashSet<CampaignProfileReport>();
            this.CampaignProfileTimeSettings = new HashSet<CampaignProfileTimeSetting>();
            this.CampaignProfileTvs = new HashSet<CampaignProfileTv>();
            this.CampaignProfileUserProfiles = new HashSet<CampaignProfileUserProfile>();
            this.Questions = new HashSet<Question>();
        }
    
        public int CampaignProfileId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string CampaignName { get; set; }
        public string CampaignDescription { get; set; }
        public float TotalBudget { get; set; }
        public float MaxDailyBudget { get; set; }
        public float MaxBid { get; set; }
        public Nullable<float> MaxMonthBudget { get; set; }
        public Nullable<float> MaxWeeklyBudget { get; set; }
        public Nullable<float> MaxHourlyBudget { get; set; }
        public Nullable<float> TotalCredit { get; set; }
        public Nullable<float> SpendToDate { get; set; }
        public float AvailableCredit { get; set; }
        public int PlaysToDate { get; set; }
        public int PlaysLastMonth { get; set; }
        public int PlaysCurrentMonth { get; set; }
        public int CancelledToDate { get; set; }
        public int CancelledLastMonth { get; set; }
        public int CancelledCurrentMonth { get; set; }
        public int SmsToDate { get; set; }
        public int SmsLastMonth { get; set; }
        public int SmsCurrentMonth { get; set; }
        public int EmailToDate { get; set; }
        public int EmailsLastMonth { get; set; }
        public int EmailsCurrentMonth { get; set; }
        public string EmailFileLocation { get; set; }
        public bool Active { get; set; }
        public int NumberOfPlays { get; set; }
        public int AverageDailyPlays { get; set; }
        public int SmsRequests { get; set; }
        public int EmailsDelievered { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string EmailSenderAddress { get; set; }
        public string SmsOriginator { get; set; }
        public string SmsBody { get; set; }
        public string SMSFileLocation { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NumberInBatch { get; set; }
    
        public virtual ICollection<Advert> Adverts { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual ICollection<BucketAuditRow> BucketAuditRows { get; set; }
        public virtual ICollection<CampaignAdvert> CampaignAdverts { get; set; }
        public virtual ICollection<CampaignAudit> CampaignAudits { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CampaignProfileAdvert> CampaignProfileAdverts { get; set; }
        public virtual ICollection<CampaignProfileAttitude> CampaignProfileAttitudes { get; set; }
        public virtual ICollection<CampaignProfileCinema> CampaignProfileCinemas { get; set; }
        public virtual ICollection<CampaignProfileDateSetting> CampaignProfileDateSettings { get; set; }
        public virtual ICollection<CampaignProfileDemographic> CampaignProfileDemographics { get; set; }
        public virtual ICollection<CampaignProfileInternet> CampaignProfileInternets { get; set; }
        public virtual ICollection<CampaignProfileMobile> CampaignProfileMobiles { get; set; }
        public virtual ICollection<CampaignProfilePress> CampaignProfilePresses { get; set; }
        public virtual ICollection<CampaignProfileProductsService> CampaignProfileProductsServices { get; set; }
        public virtual ICollection<CampaignProfileRadio> CampaignProfileRadios { get; set; }
        public virtual ICollection<CampaignProfileReport> CampaignProfileReports { get; set; }
        public virtual ICollection<CampaignProfileTimeSetting> CampaignProfileTimeSettings { get; set; }
        public virtual ICollection<CampaignProfileTv> CampaignProfileTvs { get; set; }
        public virtual ICollection<CampaignProfileUserProfile> CampaignProfileUserProfiles { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
