//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignAudit
    {
        public int CampaignAuditId { get; set; }
        public int CampaignProfileId { get; set; }
        public int UserProfileId { get; set; }
        public double BidValue { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public long PlayLengthTicks { get; set; }
        public string SMS { get; set; }
        public double SMSCost { get; set; }
        public string Email { get; set; }
        public double EmailCost { get; set; }
        public double TotalCost { get; set; }
        public string Status { get; set; }
    
        public virtual CampaignProfile CampaignProfile { get; set; }
    }
}
