//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionComments = new HashSet<QuestionComment>();
            this.QuestionImages = new HashSet<QuestionImage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string QNumber { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CampaignProfileId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> LastResponseDateTime { get; set; }
        public Nullable<System.DateTime> LastResponseDateTimeByUser { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual CampaignProfile CampaignProfile { get; set; }
        public virtual Client Client { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual QuestionSubject QuestionSubject { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuestionComment> QuestionComments { get; set; }
        public virtual ICollection<QuestionImage> QuestionImages { get; set; }
    }
}
