//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileInternet
    {
        public int UserProfileInternetId { get; set; }
        public int UserProfileId { get; set; }
        public Nullable<int> SocialNetworking { get; set; }
        public Nullable<int> Video { get; set; }
        public Nullable<int> Research { get; set; }
        public Nullable<int> Auctions { get; set; }
        public Nullable<int> Shopping { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
