//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileCreditsReceived
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public string TotalCredits { get; set; }
        public string LastMonthCredits { get; set; }
        public string CurrentMonthCredits { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
