//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Adverts = new HashSet<Advert>();
            this.Billings = new HashSet<Billing>();
            this.BlockedNumbers = new HashSet<BlockedNumber>();
            this.CampaignProfiles = new HashSet<CampaignProfile>();
            this.Clients = new HashSet<Client>();
            this.CompanyDetails = new HashSet<CompanyDetail>();
            this.Contacts = new HashSet<Contact>();
            this.Countries = new HashSet<Country>();
            this.CountryTaxes = new HashSet<CountryTax>();
            this.Questions = new HashSet<Question>();
            this.QuestionComments = new HashSet<QuestionComment>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.UsersCredits = new HashSet<UsersCredit>();
            this.UsersCreditPayments = new HashSet<UsersCreditPayment>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PasswordHash { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Organisation { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> Activated { get; set; }
        public int RoleId { get; set; }
        public bool VerificationStatus { get; set; }
        public int Outstandingdays { get; set; }
        public int OperatorId { get; set; }
    
        public virtual ICollection<Advert> Adverts { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual ICollection<BlockedNumber> BlockedNumbers { get; set; }
        public virtual ICollection<CampaignProfile> CampaignProfiles { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<CompanyDetail> CompanyDetails { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<CountryTax> CountryTaxes { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<QuestionComment> QuestionComments { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<UsersCredit> UsersCredits { get; set; }
        public virtual ICollection<UsersCreditPayment> UsersCreditPayments { get; set; }
    }
}
