//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileAttitude
    {
        public int UserProfileAttitudeId { get; set; }
        public int UserProfileId { get; set; }
        public Nullable<int> Fitness { get; set; }
        public Nullable<int> Holidays { get; set; }
        public Nullable<int> Environment { get; set; }
        public Nullable<int> GoingOut { get; set; }
        public Nullable<int> FinancialStabiity { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Fashion { get; set; }
        public Nullable<int> Music { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
