//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileAdvertsReceived
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public string AdvertRef { get; set; }
        public string AdvertName { get; set; }
        public string Brand { get; set; }
        public System.DateTime DateTimePlayed { get; set; }
        public string CreditsReceived { get; set; }
        public string FileName { get; set; }
        public string Status { get; set; }
        public Nullable<long> PlayLengthTicks { get; set; }
        public int CampaignAuditId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
