//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileAdvert
    {
        public int UserProfileAdvertsId { get; set; }
        public int UserProfileId { get; set; }
        public Nullable<int> Food { get; set; }
        public Nullable<int> SweetSaltySnacks { get; set; }
        public Nullable<int> AlcoholicDrinks { get; set; }
        public Nullable<int> NonAlcoholicDrinks { get; set; }
        public Nullable<int> Householdproducts { get; set; }
        public Nullable<int> ToiletriesCosmetics { get; set; }
        public Nullable<int> PharmaceuticalChemistsProducts { get; set; }
        public Nullable<int> TobaccoProducts { get; set; }
        public Nullable<int> PetsPetFood { get; set; }
        public Nullable<int> ShoppingRetailClothing { get; set; }
        public Nullable<int> DIYGardening { get; set; }
        public Nullable<int> AppliancesOtherHouseholdDurables { get; set; }
        public Nullable<int> ElectronicsOtherPersonalItems { get; set; }
        public Nullable<int> CommunicationsInternet { get; set; }
        public Nullable<int> FinancialServices { get; set; }
        public Nullable<int> HolidaysTravel { get; set; }
        public Nullable<int> SportsLeisure { get; set; }
        public Nullable<int> Motoring { get; set; }
        public Nullable<int> Newspapers { get; set; }
        public Nullable<int> Magazines { get; set; }
        public Nullable<int> TV { get; set; }
        public Nullable<int> Radio { get; set; }
        public Nullable<int> Cinema { get; set; }
        public Nullable<int> SocialNetworking { get; set; }
        public Nullable<int> GeneralUse { get; set; }
        public Nullable<int> Shopping { get; set; }
        public Nullable<int> Fitness { get; set; }
        public Nullable<int> Holidays { get; set; }
        public Nullable<int> Environment { get; set; }
        public Nullable<int> GoingOut { get; set; }
        public Nullable<int> FinancialProducts { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Fashion { get; set; }
        public Nullable<int> Music { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
