// <auto-generated />
namespace EFMVC.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BucketAudit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BucketAudit));
        
        string IMigrationMetadata.Id
        {
            get { return "201310091155463_BucketAudit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
