// <auto-generated />
namespace EFMVC.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdvertsReceived_Filename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdvertsReceived_Filename));
        
        string IMigrationMetadata.Id
        {
            get { return "201403281202271_AdvertsReceived_Filename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
