// <auto-generated />
namespace EFMVC.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StringToIntForCampaignQuestions2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StringToIntForCampaignQuestions2));
        
        string IMigrationMetadata.Id
        {
            get { return "201405091755314_StringToIntForCampaignQuestions2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
