namespace EFMVC.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddnewadtypeinUserProfilePreferenceandUserMatchTable : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.UserProfilePreference", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserProfilePreference", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatches", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch10", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch2", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch3", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch4", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch5", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch6", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch7", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch8", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.UserMatch9", "SkizaProfile_AdType", c => c.String(maxLength: 50));
        }
        
        public override void Down()
        {
            DropColumn("dbo.UserMatch9", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch9", "Games_AdType");
            DropColumn("dbo.UserMatch9", "RealEstate_AdType");
            DropColumn("dbo.UserMatch9", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch9", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch9", "Gifts_AdType");
            DropColumn("dbo.UserMatch9", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch9", "Healthcare_AdType");
            DropColumn("dbo.UserMatch9", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch9", "Energy_AdType");
            DropColumn("dbo.UserMatch9", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch9", "Furniture_AdType");
            DropColumn("dbo.UserMatch9", "Insurance_AdType");
            DropColumn("dbo.UserMatch9", "Restaurants_AdType");
            DropColumn("dbo.UserMatch9", "Gambling_AdType");
            DropColumn("dbo.UserMatch9", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch8", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch8", "Games_AdType");
            DropColumn("dbo.UserMatch8", "RealEstate_AdType");
            DropColumn("dbo.UserMatch8", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch8", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch8", "Gifts_AdType");
            DropColumn("dbo.UserMatch8", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch8", "Healthcare_AdType");
            DropColumn("dbo.UserMatch8", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch8", "Energy_AdType");
            DropColumn("dbo.UserMatch8", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch8", "Furniture_AdType");
            DropColumn("dbo.UserMatch8", "Insurance_AdType");
            DropColumn("dbo.UserMatch8", "Restaurants_AdType");
            DropColumn("dbo.UserMatch8", "Gambling_AdType");
            DropColumn("dbo.UserMatch8", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch7", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch7", "Games_AdType");
            DropColumn("dbo.UserMatch7", "RealEstate_AdType");
            DropColumn("dbo.UserMatch7", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch7", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch7", "Gifts_AdType");
            DropColumn("dbo.UserMatch7", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch7", "Healthcare_AdType");
            DropColumn("dbo.UserMatch7", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch7", "Energy_AdType");
            DropColumn("dbo.UserMatch7", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch7", "Furniture_AdType");
            DropColumn("dbo.UserMatch7", "Insurance_AdType");
            DropColumn("dbo.UserMatch7", "Restaurants_AdType");
            DropColumn("dbo.UserMatch7", "Gambling_AdType");
            DropColumn("dbo.UserMatch7", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch6", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch6", "Games_AdType");
            DropColumn("dbo.UserMatch6", "RealEstate_AdType");
            DropColumn("dbo.UserMatch6", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch6", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch6", "Gifts_AdType");
            DropColumn("dbo.UserMatch6", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch6", "Healthcare_AdType");
            DropColumn("dbo.UserMatch6", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch6", "Energy_AdType");
            DropColumn("dbo.UserMatch6", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch6", "Furniture_AdType");
            DropColumn("dbo.UserMatch6", "Insurance_AdType");
            DropColumn("dbo.UserMatch6", "Restaurants_AdType");
            DropColumn("dbo.UserMatch6", "Gambling_AdType");
            DropColumn("dbo.UserMatch6", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch5", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch5", "Games_AdType");
            DropColumn("dbo.UserMatch5", "RealEstate_AdType");
            DropColumn("dbo.UserMatch5", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch5", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch5", "Gifts_AdType");
            DropColumn("dbo.UserMatch5", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch5", "Healthcare_AdType");
            DropColumn("dbo.UserMatch5", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch5", "Energy_AdType");
            DropColumn("dbo.UserMatch5", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch5", "Furniture_AdType");
            DropColumn("dbo.UserMatch5", "Insurance_AdType");
            DropColumn("dbo.UserMatch5", "Restaurants_AdType");
            DropColumn("dbo.UserMatch5", "Gambling_AdType");
            DropColumn("dbo.UserMatch5", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch4", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch4", "Games_AdType");
            DropColumn("dbo.UserMatch4", "RealEstate_AdType");
            DropColumn("dbo.UserMatch4", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch4", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch4", "Gifts_AdType");
            DropColumn("dbo.UserMatch4", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch4", "Healthcare_AdType");
            DropColumn("dbo.UserMatch4", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch4", "Energy_AdType");
            DropColumn("dbo.UserMatch4", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch4", "Furniture_AdType");
            DropColumn("dbo.UserMatch4", "Insurance_AdType");
            DropColumn("dbo.UserMatch4", "Restaurants_AdType");
            DropColumn("dbo.UserMatch4", "Gambling_AdType");
            DropColumn("dbo.UserMatch4", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch3", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch3", "Games_AdType");
            DropColumn("dbo.UserMatch3", "RealEstate_AdType");
            DropColumn("dbo.UserMatch3", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch3", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch3", "Gifts_AdType");
            DropColumn("dbo.UserMatch3", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch3", "Healthcare_AdType");
            DropColumn("dbo.UserMatch3", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch3", "Energy_AdType");
            DropColumn("dbo.UserMatch3", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch3", "Furniture_AdType");
            DropColumn("dbo.UserMatch3", "Insurance_AdType");
            DropColumn("dbo.UserMatch3", "Restaurants_AdType");
            DropColumn("dbo.UserMatch3", "Gambling_AdType");
            DropColumn("dbo.UserMatch3", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch2", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch2", "Games_AdType");
            DropColumn("dbo.UserMatch2", "RealEstate_AdType");
            DropColumn("dbo.UserMatch2", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch2", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch2", "Gifts_AdType");
            DropColumn("dbo.UserMatch2", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch2", "Healthcare_AdType");
            DropColumn("dbo.UserMatch2", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch2", "Energy_AdType");
            DropColumn("dbo.UserMatch2", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch2", "Furniture_AdType");
            DropColumn("dbo.UserMatch2", "Insurance_AdType");
            DropColumn("dbo.UserMatch2", "Restaurants_AdType");
            DropColumn("dbo.UserMatch2", "Gambling_AdType");
            DropColumn("dbo.UserMatch2", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatch10", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatch10", "Games_AdType");
            DropColumn("dbo.UserMatch10", "RealEstate_AdType");
            DropColumn("dbo.UserMatch10", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatch10", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatch10", "Gifts_AdType");
            DropColumn("dbo.UserMatch10", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatch10", "Healthcare_AdType");
            DropColumn("dbo.UserMatch10", "Supermarkets_AdType");
            DropColumn("dbo.UserMatch10", "Energy_AdType");
            DropColumn("dbo.UserMatch10", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatch10", "Furniture_AdType");
            DropColumn("dbo.UserMatch10", "Insurance_AdType");
            DropColumn("dbo.UserMatch10", "Restaurants_AdType");
            DropColumn("dbo.UserMatch10", "Gambling_AdType");
            DropColumn("dbo.UserMatch10", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserMatches", "SkizaProfile_AdType");
            DropColumn("dbo.UserMatches", "Games_AdType");
            DropColumn("dbo.UserMatches", "RealEstate_AdType");
            DropColumn("dbo.UserMatches", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserMatches", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserMatches", "Gifts_AdType");
            DropColumn("dbo.UserMatches", "JobsAndEducation_AdType");
            DropColumn("dbo.UserMatches", "Healthcare_AdType");
            DropColumn("dbo.UserMatches", "Supermarkets_AdType");
            DropColumn("dbo.UserMatches", "Energy_AdType");
            DropColumn("dbo.UserMatches", "InformationTechnology_AdType");
            DropColumn("dbo.UserMatches", "Furniture_AdType");
            DropColumn("dbo.UserMatches", "Insurance_AdType");
            DropColumn("dbo.UserMatches", "Restaurants_AdType");
            DropColumn("dbo.UserMatches", "Gambling_AdType");
            DropColumn("dbo.UserMatches", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.UserProfilePreference", "SkizaProfile_AdType");
            DropColumn("dbo.UserProfilePreference", "Games_AdType");
            DropColumn("dbo.UserProfilePreference", "RealEstate_AdType");
            DropColumn("dbo.UserProfilePreference", "DatingAndPersonal_AdType");
            DropColumn("dbo.UserProfilePreference", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.UserProfilePreference", "Gifts_AdType");
            DropColumn("dbo.UserProfilePreference", "JobsAndEducation_AdType");
            DropColumn("dbo.UserProfilePreference", "Healthcare_AdType");
            DropColumn("dbo.UserProfilePreference", "Supermarkets_AdType");
            DropColumn("dbo.UserProfilePreference", "Energy_AdType");
            DropColumn("dbo.UserProfilePreference", "InformationTechnology_AdType");
            DropColumn("dbo.UserProfilePreference", "Furniture_AdType");
            DropColumn("dbo.UserProfilePreference", "Insurance_AdType");
            DropColumn("dbo.UserProfilePreference", "Restaurants_AdType");
            DropColumn("dbo.UserProfilePreference", "Gambling_AdType");
            DropColumn("dbo.UserProfilePreference", "BusinessOrOpportunities_AdType");
        }
    }
}
