namespace EFMVC.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddNewAdTypeFieldinCampaignProfilePrefernceandCampaignMatch : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CampaignProfilePreference", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignProfilePreference", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatches", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch10", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch2", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch3", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch4", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch5", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch6", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch7", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch8", "SkizaProfile_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "BusinessOrOpportunities_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Gambling_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Restaurants_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Insurance_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Furniture_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "InformationTechnology_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Energy_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Supermarkets_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Healthcare_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "JobsAndEducation_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Gifts_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "AdvocacyOrLegal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "DatingAndPersonal_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "RealEstate_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "Games_AdType", c => c.String(maxLength: 50));
            AddColumn("dbo.CampaignMatch9", "SkizaProfile_AdType", c => c.String(maxLength: 50));
        }
        
        public override void Down()
        {
            DropColumn("dbo.CampaignMatch9", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch9", "Games_AdType");
            DropColumn("dbo.CampaignMatch9", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch9", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch9", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch9", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch9", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch9", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch9", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch9", "Energy_AdType");
            DropColumn("dbo.CampaignMatch9", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch9", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch9", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch9", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch9", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch9", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch8", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch8", "Games_AdType");
            DropColumn("dbo.CampaignMatch8", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch8", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch8", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch8", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch8", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch8", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch8", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch8", "Energy_AdType");
            DropColumn("dbo.CampaignMatch8", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch8", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch8", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch8", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch8", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch8", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch7", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch7", "Games_AdType");
            DropColumn("dbo.CampaignMatch7", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch7", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch7", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch7", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch7", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch7", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch7", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch7", "Energy_AdType");
            DropColumn("dbo.CampaignMatch7", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch7", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch7", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch7", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch7", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch7", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch6", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch6", "Games_AdType");
            DropColumn("dbo.CampaignMatch6", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch6", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch6", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch6", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch6", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch6", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch6", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch6", "Energy_AdType");
            DropColumn("dbo.CampaignMatch6", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch6", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch6", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch6", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch6", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch6", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch5", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch5", "Games_AdType");
            DropColumn("dbo.CampaignMatch5", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch5", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch5", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch5", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch5", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch5", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch5", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch5", "Energy_AdType");
            DropColumn("dbo.CampaignMatch5", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch5", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch5", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch5", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch5", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch5", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch4", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch4", "Games_AdType");
            DropColumn("dbo.CampaignMatch4", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch4", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch4", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch4", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch4", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch4", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch4", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch4", "Energy_AdType");
            DropColumn("dbo.CampaignMatch4", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch4", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch4", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch4", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch4", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch4", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch3", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch3", "Games_AdType");
            DropColumn("dbo.CampaignMatch3", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch3", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch3", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch3", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch3", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch3", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch3", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch3", "Energy_AdType");
            DropColumn("dbo.CampaignMatch3", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch3", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch3", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch3", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch3", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch3", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch2", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch2", "Games_AdType");
            DropColumn("dbo.CampaignMatch2", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch2", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch2", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch2", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch2", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch2", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch2", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch2", "Energy_AdType");
            DropColumn("dbo.CampaignMatch2", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch2", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch2", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch2", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch2", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch2", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatch10", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatch10", "Games_AdType");
            DropColumn("dbo.CampaignMatch10", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatch10", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatch10", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatch10", "Gifts_AdType");
            DropColumn("dbo.CampaignMatch10", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatch10", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatch10", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatch10", "Energy_AdType");
            DropColumn("dbo.CampaignMatch10", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatch10", "Furniture_AdType");
            DropColumn("dbo.CampaignMatch10", "Insurance_AdType");
            DropColumn("dbo.CampaignMatch10", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatch10", "Gambling_AdType");
            DropColumn("dbo.CampaignMatch10", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignMatches", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignMatches", "Games_AdType");
            DropColumn("dbo.CampaignMatches", "RealEstate_AdType");
            DropColumn("dbo.CampaignMatches", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignMatches", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignMatches", "Gifts_AdType");
            DropColumn("dbo.CampaignMatches", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignMatches", "Healthcare_AdType");
            DropColumn("dbo.CampaignMatches", "Supermarkets_AdType");
            DropColumn("dbo.CampaignMatches", "Energy_AdType");
            DropColumn("dbo.CampaignMatches", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignMatches", "Furniture_AdType");
            DropColumn("dbo.CampaignMatches", "Insurance_AdType");
            DropColumn("dbo.CampaignMatches", "Restaurants_AdType");
            DropColumn("dbo.CampaignMatches", "Gambling_AdType");
            DropColumn("dbo.CampaignMatches", "BusinessOrOpportunities_AdType");
            DropColumn("dbo.CampaignProfilePreference", "SkizaProfile_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Games_AdType");
            DropColumn("dbo.CampaignProfilePreference", "RealEstate_AdType");
            DropColumn("dbo.CampaignProfilePreference", "DatingAndPersonal_AdType");
            DropColumn("dbo.CampaignProfilePreference", "AdvocacyOrLegal_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Gifts_AdType");
            DropColumn("dbo.CampaignProfilePreference", "JobsAndEducation_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Healthcare_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Supermarkets_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Energy_AdType");
            DropColumn("dbo.CampaignProfilePreference", "InformationTechnology_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Furniture_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Insurance_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Restaurants_AdType");
            DropColumn("dbo.CampaignProfilePreference", "Gambling_AdType");
            DropColumn("dbo.CampaignProfilePreference", "BusinessOrOpportunities_AdType");
        }
    }
}
