// <auto-generated />
namespace EFMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddCountryIdinClienttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCountryIdinClienttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201903010547146_Add CountryId in Client table "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
