namespace EFMVC.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UpdateCampaignAudit2to10andUserProfileAdvertsReceived2to10Table : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.UserProfileAdvertsReceived10", "CampaignAuditId", "dbo.CampaignAudit10");
            DropForeignKey("dbo.UserProfileAdvertsReceived2", "CampaignAuditId", "dbo.CampaignAudit2");
            DropForeignKey("dbo.UserProfileAdvertsReceived3", "CampaignAuditId", "dbo.CampaignAudit3");
            DropForeignKey("dbo.UserProfileAdvertsReceived4", "CampaignAuditId", "dbo.CampaignAudit4");
            DropForeignKey("dbo.UserProfileAdvertsReceived5", "CampaignAuditId", "dbo.CampaignAudit5");
            DropForeignKey("dbo.UserProfileAdvertsReceived6", "CampaignAuditId", "dbo.CampaignAudit6");
            DropForeignKey("dbo.UserProfileAdvertsReceived7", "CampaignAuditId", "dbo.CampaignAudit7");
            DropForeignKey("dbo.UserProfileAdvertsReceived8", "CampaignAuditId", "dbo.CampaignAudit8");
            DropForeignKey("dbo.UserProfileAdvertsReceived9", "CampaignAuditId", "dbo.CampaignAudit9");
            DropIndex("dbo.UserProfileAdvertsReceived10", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived2", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived3", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived4", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived5", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived6", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived7", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived8", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived9", new[] { "CampaignAuditId" });
            AddColumn("dbo.UserProfileAdvertsReceived10", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived10", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived10", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit10", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit10", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit10", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit10", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit10", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived2", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived2", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived2", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit2", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit2", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit2", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit2", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit2", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived3", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived3", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived3", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit3", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit3", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit3", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit3", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit3", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived4", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived4", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived4", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit4", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit4", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit4", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit4", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit4", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived5", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived5", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived5", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit5", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit5", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit5", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit5", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit5", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived6", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived6", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived6", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit6", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit6", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit6", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit6", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit6", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived7", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived7", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived7", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit7", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit7", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit7", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit7", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit7", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived8", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived8", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived8", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit8", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit8", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit8", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit8", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit8", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived9", "IsMaxAdvertPerDay", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived9", "IsRewardReceived", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserProfileAdvertsReceived9", "UnUsedCredit", c => c.String());
            AddColumn("dbo.CampaignAudit9", "IsMerticsUpdated", c => c.Boolean(nullable: false));
            AddColumn("dbo.CampaignAudit9", "CampaignAuditTableName", c => c.String());
            AddColumn("dbo.CampaignAudit9", "AdtoneServerCampaignProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit9", "AdtoneServerUserProfileId", c => c.Int());
            AddColumn("dbo.CampaignAudit9", "AdtoneServerDataTransfer", c => c.Boolean(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived10", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived2", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived3", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived4", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived5", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived6", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived7", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived8", "CampaignAuditId", c => c.Int());
            AlterColumn("dbo.UserProfileAdvertsReceived9", "CampaignAuditId", c => c.Int());
            CreateIndex("dbo.UserProfileAdvertsReceived10", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived2", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived3", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived4", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived5", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived6", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived7", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived8", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived9", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived10", "CampaignAuditId", "dbo.CampaignAudit10", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived2", "CampaignAuditId", "dbo.CampaignAudit2", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived3", "CampaignAuditId", "dbo.CampaignAudit3", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived4", "CampaignAuditId", "dbo.CampaignAudit4", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived5", "CampaignAuditId", "dbo.CampaignAudit5", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived6", "CampaignAuditId", "dbo.CampaignAudit6", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived7", "CampaignAuditId", "dbo.CampaignAudit7", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived8", "CampaignAuditId", "dbo.CampaignAudit8", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived9", "CampaignAuditId", "dbo.CampaignAudit9", "CampaignAuditId");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UserProfileAdvertsReceived9", "CampaignAuditId", "dbo.CampaignAudit9");
            DropForeignKey("dbo.UserProfileAdvertsReceived8", "CampaignAuditId", "dbo.CampaignAudit8");
            DropForeignKey("dbo.UserProfileAdvertsReceived7", "CampaignAuditId", "dbo.CampaignAudit7");
            DropForeignKey("dbo.UserProfileAdvertsReceived6", "CampaignAuditId", "dbo.CampaignAudit6");
            DropForeignKey("dbo.UserProfileAdvertsReceived5", "CampaignAuditId", "dbo.CampaignAudit5");
            DropForeignKey("dbo.UserProfileAdvertsReceived4", "CampaignAuditId", "dbo.CampaignAudit4");
            DropForeignKey("dbo.UserProfileAdvertsReceived3", "CampaignAuditId", "dbo.CampaignAudit3");
            DropForeignKey("dbo.UserProfileAdvertsReceived2", "CampaignAuditId", "dbo.CampaignAudit2");
            DropForeignKey("dbo.UserProfileAdvertsReceived10", "CampaignAuditId", "dbo.CampaignAudit10");
            DropIndex("dbo.UserProfileAdvertsReceived9", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived8", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived7", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived6", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived5", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived4", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived3", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived2", new[] { "CampaignAuditId" });
            DropIndex("dbo.UserProfileAdvertsReceived10", new[] { "CampaignAuditId" });
            AlterColumn("dbo.UserProfileAdvertsReceived9", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived8", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived7", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived6", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived5", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived4", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived3", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived2", "CampaignAuditId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserProfileAdvertsReceived10", "CampaignAuditId", c => c.Int(nullable: false));
            DropColumn("dbo.CampaignAudit9", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit9", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit9", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit9", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit9", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived9", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived9", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived9", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit8", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit8", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit8", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit8", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit8", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived8", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived8", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived8", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit7", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit7", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit7", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit7", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit7", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived7", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived7", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived7", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit6", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit6", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit6", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit6", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit6", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived6", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived6", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived6", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit5", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit5", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit5", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit5", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit5", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived5", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived5", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived5", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit4", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit4", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit4", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit4", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit4", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived4", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived4", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived4", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit3", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit3", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit3", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit3", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit3", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived3", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived3", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived3", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit2", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit2", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit2", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit2", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit2", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived2", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived2", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived2", "IsMaxAdvertPerDay");
            DropColumn("dbo.CampaignAudit10", "AdtoneServerDataTransfer");
            DropColumn("dbo.CampaignAudit10", "AdtoneServerUserProfileId");
            DropColumn("dbo.CampaignAudit10", "AdtoneServerCampaignProfileId");
            DropColumn("dbo.CampaignAudit10", "CampaignAuditTableName");
            DropColumn("dbo.CampaignAudit10", "IsMerticsUpdated");
            DropColumn("dbo.UserProfileAdvertsReceived10", "UnUsedCredit");
            DropColumn("dbo.UserProfileAdvertsReceived10", "IsRewardReceived");
            DropColumn("dbo.UserProfileAdvertsReceived10", "IsMaxAdvertPerDay");
            CreateIndex("dbo.UserProfileAdvertsReceived9", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived8", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived7", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived6", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived5", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived4", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived3", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived2", "CampaignAuditId");
            CreateIndex("dbo.UserProfileAdvertsReceived10", "CampaignAuditId");
            AddForeignKey("dbo.UserProfileAdvertsReceived9", "CampaignAuditId", "dbo.CampaignAudit9", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived8", "CampaignAuditId", "dbo.CampaignAudit8", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived7", "CampaignAuditId", "dbo.CampaignAudit7", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived6", "CampaignAuditId", "dbo.CampaignAudit6", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived5", "CampaignAuditId", "dbo.CampaignAudit5", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived4", "CampaignAuditId", "dbo.CampaignAudit4", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived3", "CampaignAuditId", "dbo.CampaignAudit3", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived2", "CampaignAuditId", "dbo.CampaignAudit2", "CampaignAuditId", cascadeDelete: true);
            AddForeignKey("dbo.UserProfileAdvertsReceived10", "CampaignAuditId", "dbo.CampaignAudit10", "CampaignAuditId", cascadeDelete: true);
        }
    }
}
