// <auto-generated />
namespace EFMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class UpdateCampaignAudit2to10andUserProfileAdvertsReceived2to10Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateCampaignAudit2to10andUserProfileAdvertsReceived2to10Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201912031210302_Update CampaignAudit 2to10 and UserProfileAdvertsReceived 2to10 Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
