// <auto-generated />
namespace EFMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddPromotionalUserIdFieldinBucket1To10andPromotionalCampaignIdFieldinBucketItem1To10Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPromotionalUserIdFieldinBucket1To10andPromotionalCampaignIdFieldinBucketItem1To10Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202001291308503_Add PromotionalUserId Field in Bucket1To10 and PromotionalCampaignId Field in BucketItem1To10 Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
