//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtharEntities1 : DbContext
    {
        public ArtharEntities1()
            : base("name=ArtharEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<BlockedNumber> BlockedNumbers { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserProfileAdvert> UserProfileAdverts { get; set; }
        public DbSet<UserProfileAttitude> UserProfileAttitudes { get; set; }
        public DbSet<UserProfileCinema> UserProfileCinemas { get; set; }
        public DbSet<UserProfileInternet> UserProfileInternets { get; set; }
        public DbSet<UserProfileMobile> UserProfileMobiles { get; set; }
        public DbSet<UserProfilePress> UserProfilePresses { get; set; }
        public DbSet<UserProfileProductsService> UserProfileProductsServices { get; set; }
        public DbSet<UserProfileRadio> UserProfileRadios { get; set; }
        public DbSet<UserProfileTimeSetting> UserProfileTimeSettings { get; set; }
        public DbSet<UserProfileTv> UserProfileTvs { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
