//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileCinema
    {
        public int UserProfileCinemaId { get; set; }
        public int UserProfileId { get; set; }
        public Nullable<int> Cinema { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
