//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.ProvisioningModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class add_play_check
    {
        public string MSISDN { get; set; }
        public int BUCKET_ID { get; set; }
        public Nullable<int> BUCKET_BATCH_ID { get; set; }
        public string BATCH_STATUS { get; set; }
        public Nullable<int> ITEM_TOTAL { get; set; }
        public int ITEM_ID { get; set; }
        public Nullable<int> ADD_STATE_ID { get; set; }
        public string ADD_STATE { get; set; }
        public int PRIORITY { get; set; }
        public string MEDIA_URL { get; set; }
    }
}
