//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.ProvisioningModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUCKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUCKET()
        {
            this.BUCKET_ITEM = new HashSet<BUCKET_ITEM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BUCKET_BATCH_ID { get; set; }
        public string MSISDN { get; set; }
        public Nullable<int> ITEM_TOTAL { get; set; }
        public string EMAIL_ADDRESS { get; set; }
    
        public virtual BUCKET_BATCH BUCKET_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUCKET_ITEM> BUCKET_ITEM { get; set; }
    }
}
