//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVC.ProvisioningModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class arthar_addcache_provisioningEntities4 : DbContext
    {
        public arthar_addcache_provisioningEntities4()
            : base("name=arthar_addcache_provisioningEntities4")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 3600;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ACCOUNT_OPT_OUT> ACCOUNT_OPT_OUT { get; set; }
        public virtual DbSet<ADD_STATE> ADD_STATE { get; set; }
        public virtual DbSet<BUCKET> BUCKETs { get; set; }
        public virtual DbSet<BUCKET_BATCH> BUCKET_BATCH { get; set; }
        public virtual DbSet<BUCKET_BATCH_STATUS> BUCKET_BATCH_STATUS { get; set; }
        public virtual DbSet<BUCKET_ITEM> BUCKET_ITEM { get; set; }
        public virtual DbSet<campaignmatchusermatch> campaignmatchusermatches { get; set; }
        public virtual DbSet<campaignprofiletimesetting> campaignprofiletimesettings { get; set; }
        public virtual DbSet<usermatch> usermatches { get; set; }
        public virtual DbSet<userprofiletimesetting> userprofiletimesettings { get; set; }
        public virtual DbSet<add_play_check> add_play_check { get; set; }
        public virtual DbSet<campaignmatch> campaignmatches { get; set; }

        public virtual int uspa_bucket_prcess(Nullable<int> timesettings, Nullable<int> vHour, Nullable<int> adslimit)
        {
            var timesettingsParameter = timesettings.HasValue ?
                new ObjectParameter("timesettings", timesettings) :
                new ObjectParameter("timesettings", typeof(int));

            var vHourParameter = vHour.HasValue ?
                new ObjectParameter("vHour", vHour) :
                new ObjectParameter("vHour", typeof(int));

            var adslimitParameter = adslimit.HasValue ?
                new ObjectParameter("adslimit", adslimit) :
                new ObjectParameter("adslimit", typeof(int));

            var obj = ((IObjectContextAdapter)this).ObjectContext;
            obj.CommandTimeout = 18000; // 3600

            return obj.ExecuteFunction("uspa_bucket_prcess", timesettingsParameter, vHourParameter, adslimitParameter);
        }

        public virtual int uspa_campaign_user_match(Nullable<int> campmatchlimit)
        {
            var campmatchlimitParameter = campmatchlimit.HasValue ?
                new ObjectParameter("campmatchlimit", campmatchlimit) :
                new ObjectParameter("campmatchlimit", typeof(int));

            var obj2 = ((IObjectContextAdapter)this).ObjectContext;
            obj2.CommandTimeout = 3600;

            return obj2.ExecuteFunction("uspa_campaign_user_match", campmatchlimitParameter);
        }

        public virtual int uspa_delete_spent_records()
        {
            var obj3 = ((IObjectContextAdapter)this).ObjectContext;
            obj3.CommandTimeout = 3600;
            return obj3.ExecuteFunction("uspa_delete_spent_records");
        }

        public virtual int uspa_delete_spent_records10()
        {
            var obj4 = ((IObjectContextAdapter)this).ObjectContext;
            obj4.CommandTimeout = 3600;
            return obj4.ExecuteFunction("uspa_delete_spent_records10");
        }

        public virtual int uspa_delete_spent_records2()
        {
            var obj5 = ((IObjectContextAdapter)this).ObjectContext;
            obj5.CommandTimeout = 3600;
            return obj5.ExecuteFunction("uspa_delete_spent_records2");
        }

        public virtual int uspa_delete_spent_records3()
        {
            var obj6 = ((IObjectContextAdapter)this).ObjectContext;
            obj6.CommandTimeout = 3600;
            return obj6.ExecuteFunction("uspa_delete_spent_records3");
        }

        public virtual int uspa_delete_spent_records4()
        {
            var obj7 = ((IObjectContextAdapter)this).ObjectContext;
            obj7.CommandTimeout = 3600;
            return obj7.ExecuteFunction("uspa_delete_spent_records4");
        }

        public virtual int uspa_delete_spent_records5()
        {
            var obj8 = ((IObjectContextAdapter)this).ObjectContext;
            obj8.CommandTimeout = 3600;
            return obj8.ExecuteFunction("uspa_delete_spent_records5");
        }

        public virtual int uspa_delete_spent_records6()
        {
            var obj9 = ((IObjectContextAdapter)this).ObjectContext;
            obj9.CommandTimeout = 3600;
            return obj9.ExecuteFunction("uspa_delete_spent_records6");
        }

        public virtual int uspa_delete_spent_records7()
        {
            var obj10 = ((IObjectContextAdapter)this).ObjectContext;
            obj10.CommandTimeout = 3600;
            return obj10.ExecuteFunction("uspa_delete_spent_records7");
        }

        public virtual int uspa_delete_spent_records8()
        {
            var obj11 = ((IObjectContextAdapter)this).ObjectContext;
            obj11.CommandTimeout = 3600;
            return obj11.ExecuteFunction("uspa_delete_spent_records8");
        }

        public virtual int uspa_delete_spent_records9()
        {
            var obj12 = ((IObjectContextAdapter)this).ObjectContext;
            obj12.CommandTimeout = 3600;
            return obj12.ExecuteFunction("uspa_delete_spent_records9");
        }
    }
}
